global:
  scrape_interval: 15s # Intervalle global de collecte des métriques
  evaluation_interval: 15s # Intervalle d'évaluation des règles
  external_labels:
    monitor: 'biblio-monitor' # Étiquette utilisée pour identifier la source des métriques

rule_files:
- /etc/prometheus/alert.yml # Fichier des règles d'alertes

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093 # URL du service Alertmanager

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'prometheus:9090' ]
  
- job_name: 'mysql-exporter'
  static_configs:
  - targets: [ 'mysql-exporter:9104' ]
 

- job_name: 'biblio-api'
  static_configs:
  - targets: [ 'biblio_api:8082' ]
  metrics_path: /metrics

- job_name: 'biblio-app'
  static_configs:
  - targets: [ 'biblio_app:8083' ]
  metrics_path: /metrics

- job_name: 'mysql'
  static_configs:
  - targets: [ 'mysql:3306' ]

- job_name: 'elasticsearch'
  metrics_path: /_prometheus/metrics
  static_configs:
  - targets: [ 'elasticsearch:14269' ]
  
  